name: Generate Pacman Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: hugopm/pacman-contribution-graph@v1.3.0
        with:
          github_user_name: mttahai
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_path_light: dist/pacman.svg
          output_path_dark: dist/pacman-dark.svg

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
          keep_files: true
          force_orphan: false
